server:
  port: 8086
spring :
  datasource :
    url : jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?${DB_PARAM}
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}
    driver-class-name : com.mysql.cj.jdbc.Driver
    hikari :
      pool-name : YcHikariPool
      maximum-pool-size : 20
      connection-init-sql : "SET NAMES 'utf8mb4'"
      max-lifetime : 30000

  jpa :
    hibernate :
      ddl-auto : update
      dialect : org.hibernate.dialect.MySQL8Dialect
    show-sql : false
    properties :
      hibernate :
        jdbc :
          time_zone : "Asia/Hong_Kong"
line.bot:
  push:
    url: 'https://api.line.me/v2/bot/message/push'
  channel-token: '/KDvSta1XKaqMk32FX+tAjsgGSXK+d0hKDzuvpdbhlEgIQJ+If3PKc5Bu2U0bsOLUyEHbvjDI8s5ggCj1TU7qRVu94CuUQH16iSgCg6mN6/QDhUFqXudHLnh/lksr41e28gfkVdmRthOazTONeMk9gdB04t89/1O/w1cDnyilFU='
  channel-secret: 'e7445853b00d9657adeb4a5d572eb866'
  handler.path: /callback


